//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCukApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCukApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã được sử dụng. Vui lòng thử mã khác..
        /// </summary>
        public static string CustomerCode_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerCode_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được để trống..
        /// </summary>
        public static string CustomerCode_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerCode_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email khách hàng không được để trống..
        /// </summary>
        public static string CustomerEmail_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerEmail_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email khách hàng không đúng định dạng.
        /// </summary>
        public static string CustomerEmail_Invalid_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerEmail_Invalid_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không tồn tại.
        /// </summary>
        public static string CustomerId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId không tồn tại.
        /// </summary>
        public static string Dev_CustomerId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_CustomerId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId không tồn tại.
        /// </summary>
        public static string Dev_EmployeeId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_EmployeeId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã được sử dụng. Vui lòng thử mã khác..
        /// </summary>
        public static string EmployeeCode_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeCode_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string EmployeeCode_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeCode_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nhân viên không được để trống..
        /// </summary>
        public static string EmployeeEmail_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeEmail_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nhân viên không đúng định dạng.
        /// </summary>
        public static string EmployeeEmail_Invalid_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeEmail_Invalid_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên không tồn tại.
        /// </summary>
        public static string EmployeeId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        public static string Exception_ErrorMsg {
            get {
                return ResourceManager.GetString("Exception_ErrorMsg", resourceCulture);
            }
        }
    }
}
