//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã được sử dụng. Vui lòng thử mã khác..
        /// </summary>
        internal static string CustomerCode_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerCode_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được để trống..
        /// </summary>
        internal static string CustomerCode_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerCode_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email khách hàng không được để trống..
        /// </summary>
        internal static string CustomerEmail_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerEmail_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email khách hàng không đúng định dạng.
        /// </summary>
        internal static string CustomerEmail_Invalid_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerEmail_Invalid_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng không tồn tại.
        /// </summary>
        internal static string CustomerGroupId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerGroupId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm khách hàng đã được sử dụng. Vui lòng thử tên khác..
        /// </summary>
        internal static string CustomerGroupName_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerGroupName_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không tồn tại.
        /// </summary>
        internal static string CustomerId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("CustomerId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban đã được sử dụng. Vui lòng thử với mã khác..
        /// </summary>
        internal static string DepartmentCode_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("DepartmentCode_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được để trống.
        /// </summary>
        internal static string DepartmentCode_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("DepartmentCode_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại.
        /// </summary>
        internal static string DepartmentId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("DepartmentId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban đã được sử dụng. Vui lòng thử với tên khác..
        /// </summary>
        internal static string DepartmentName_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("DepartmentName_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được để trống.
        /// </summary>
        internal static string DepartmentName_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("DepartmentName_Empty_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerGroupId không tồn tại.
        /// </summary>
        internal static string Dev_CustomerGroupId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_CustomerGroupId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerGroupName đã tồn tại.
        /// </summary>
        internal static string Dev_CustomerGroupName_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_CustomerGroupName_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId không tồn tại.
        /// </summary>
        internal static string Dev_CustomerId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_CustomerId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentId không tồn tại.
        /// </summary>
        internal static string Dev_DepartmentId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_DepartmentId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId không tồn tại.
        /// </summary>
        internal static string Dev_EmployeeId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_EmployeeId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionId không tồn tại.
        /// </summary>
        internal static string Dev_PositionId_NonExist_ErrorMsg {
            get {
                return ResourceManager.GetString("Dev_PositionId_NonExist_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã được sử dụng. Vui lòng thử mã khác..
        /// </summary>
        internal static string EmployeeCode_Duplicate_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeCode_Duplicate_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        internal static string EmployeeCode_Empty_ErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeCode_Empty_ErrorMsg", resourceCulture);
            }
        }
    }
}
